# Generated by Django 3.0.3 on 2022-07-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_statusupdate'),
        ('users', '0002_auto_20220710_0721'),
    ]

    operations = [
    ]
