# Generated by Django 3.0.3 on 2022-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220721_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
