# Generated by Django 3.0.3 on 2022-07-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contactrequest_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactRequest',
            new_name='ConnectionRequest',
        ),
    ]
